on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Build Go Binary
      run: |
        env GOARCH=amd64 GOOS=linux go build -o app .

    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: app

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download Binary Artifact
      uses: actions/download-artifact@v2
      with:
        name: app-artifact
        path: app-artifact

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Copy Go Binary to Remote Server
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} scp ./app-artifact/app ${{ secrets.VM }}:${{ secrets.PATH }}